// O'zbek tilidagi barcha matnlar
export const uz = {
  appName: "Birga Tomosha",
  tagline: "Do'stlaringiz bilan bir vaqtda kino ko'ring",
  // Auth
  signIn: "Kirish",
  signUp: "Ro'yxatdan o'tish",
  signOut: "Chiqish",
  email: "Elektron pochta",
  password: "Parol",
  displayName: "Ismingiz",
  google: "Google orqali kirish",
  authError: "Xatolik yuz berdi",
  invalidCreds: "Email yoki parol noto'g'ri",
  emailExists: "Bu email allaqachon ro'yxatdan o'tgan",
  weakPassword: "Parol kamida 6 ta belgidan iborat bo'lishi kerak",
  haveAccount: "Hisobingiz bormi?",
  noAccount: "Hisobingiz yo'qmi?",
  // Dashboard
  myRooms: "Mening xonalarim",
  createRoom: "Yangi xona yaratish",
  roomName: "Xona nomi",
  noRooms: "Hali xona yaratmagansiz",
  enter: "Kirish",
  delete: "O'chirish",
  // Room
  copyLink: "Havolani nusxalash",
  linkCopied: "Havola nusxalandi",
  theaterMode: "Kino rejimi",
  exitTheater: "Kino rejimidan chiqish",
  leave: "Chiqish",
  uploadVideo: "Video yuklash",
  externalUrl: "Tashqi URL qo'shish",
  pasteUrl: "mp4 yoki webm havolasini joylashtiring",
  invalidUrl: "Iltimos, to'g'ri .mp4 yoki .webm havolasini kiriting",
  uploading: "Yuklanmoqda",
  noVideo: "Hali video tanlanmagan",
  noVideoHint: "Xona yaratuvchisi video yuklashi yoki havola qo'shishi kerak",
  hostOnly: "Faqat xona yaratuvchisi boshqaradi",
  guests: "Mehmonlar",
  host: "Yaratuvchi",
  participants: "Ishtirokchilar",
  chat: "Chat",
  cameras: "Kameralar",
  sendMessage: "Xabar yozing...",
  send: "Yuborish",
  // Status
  joined: "Kirdi",
  loadingStatus: "Yuklanmoqda",
  ready: "Tayyor",
  waitingFor: (name: string) => `Kuting, ${name} tarmog'i qotib qoldi...`,
  // Camera
  micOn: "Mikrofonni o'chirish",
  micOff: "Mikrofonni yoqish",
  camOn: "Kamerani o'chirish",
  camOff: "Kamerani yoqish",
  permError: "Kamera va mikrofonga ruxsat bering",
  permRetry: "Qayta urinish",
  watchOnly: "Faqat tomosha rejimi",
  // Nuke
  nuke: "Serverdan tozalash",
  nukeWarning: "Diqqat! Bu video serverdan butunlay o'chiriladi. Rozimisiz?",
  confirm: "Ha, o'chirish",
  cancel: "Bekor qilish",
  videoDeleted: "Video o'chirildi",
  // Errors
  networkError: "Internet aloqasi yo'q",
  reconnecting: "Qayta ulanmoqda...",
  unknownError: "Noma'lum xatolik",
  notFound: "Topilmadi",
  goHome: "Bosh sahifa",
  loading: "Yuklanmoqda...",
  hostLeft: "Xona yaratuvchisi chiqib ketdi",
} as const;
